### ISSUE TITLE
No README

### ISSUE THREAD

**Issue by lifeiscontent** [bigcartel/middleman-imgix#1]
@mattwigham  any chance you could write a readme on how to use your gem?

**Comment by mattwigham** [comment]
Hey there, thanks for the reminder. I'll definitely try to get to this, but in the meantime the [options](https://github.com/bigcartel/middleman-imgix/blob/master/lib/middleman-imgix/extension.rb#L4-L15) are pretty well documented, and they coincide with those on the [imgix gem](https://github.com/imgix/imgix-rb) itself.

**Comment by mattwigham** [comment]
Alright, wrapped this up and officially launched the gem. Holler if you run into any questions or issues. https://github.com/bigcartel/middleman-imgix
